owner: rheinklang
repo: upptime 

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: Website
    url: https://rheinklang.events
    icon: https://rheinklang.events/favicon.png
  - name: Bio Links
    url: https://bio.rheinklang.events/links
    icon: https://www.switchy.io/assets/favicons/favicon.ico
  - name: CMS
    url: $SITE_CMS
    icon: https://getcockpit.com/favicon.png
  - name: Accounting
    url: $SITE_ACCOUNTING
    icon: https://assets.akaunting.com/site/img/logo/akaunting-logo.ico
  - name: Kanboard
    url: $SITE_KANBOARD
    icon: https://kanboard.rheinklang.events/assets/img/favicon.png

status-website:
  cname: status.rheinklang.events
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Eine Übersicht über die Stati unserer Services."
  introMessage: Die dargestellten Daten werden in **echtzeit** aus unserem [GitHub repository](https://github.com/rheinklang/uptime) aggregiert.
  customHeadHtml: "<script>var _mtm = window._mtm = window._mtm || [];_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];g.async=true; g.src='https://analytics.rheinklang.events/js/container_YSfneGKs.js'; s.parentNode.insertBefore(g,s);</script>"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://rheinklang.events
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
